### ISSUE TITLE
Port all our websites to HTTPs

### ISSUE THREAD

**Issue by simboss** [geosolutions-it/aparma#13]
- [x] geo-solutions.it #25

- [x] demo.geo-solutions.it

- [x] analytics.geo-solutions.it
- [x] logstash.geo-solutions.it

- [x] maven.geo-solutions.it #27
- [x] opensdi.geo-solutions.it
- [x] geobatch.geo-solutions.it
- [x] geonetwork.geo-solutions.it

- [x] build.geo-solutions.it
- [x] geoserver.geo-solutions.it #26
- [x] training.geonode.geo-solutions.it

- [x] mapstore.geo-solutions.it
- [x] qa.mapstore.geo-solutions.it
- [x] dev.mapstore.geo-solutions.it
- [x] mapstore2.geo-solutions.it
- [x] qa.mapstore2.geo-solutions.it
- [x] dev.mapstore2.geo-solutions.it
- [x]  lf.mapstore2.geo-solutions.it

- [x] cloudsdi.geo-solutions.it

**Comment by randomorder** [comment]
- geobatch.geo-solutions.it throws a 404 error
- cache for geo-solutions.it need to be truncated
